### ISSUE TITLE
WP_SENTRY_BROWSER_DSN and WP_SENTRY_VERSION not working

### ISSUE THREAD

**Issue by Giacomo92** [stayallive/wp-sentry#92] opened 2021-06-29 12:38 UTC
HI everyone,
I have activated the plugin and I have setup the configuration key on wp-config.php like this:

```
define('WP_SENTRY_PHP_DSN', 'MY_PHP_URL');
define('WP_SENTRY_BROWSER_DSN', 'MY_JS_URL');
```
This is a screen from admin panel:

![Schermata 2021-06-29 alle 14 34 41](https://user-images.githubusercontent.com/11694429/123798087-25e8f080-d8e7-11eb-8530-c7e0884b0469.png)

As you can see the js tracing is not enabled. 
I also tested `WP_ENVIRONMENT_TYPE` that is not working.

How can I solve this?

**Comment by stayallive** [comment] 2021-06-29 12:52
Okay, fir the `WP_ENVIRONMENT_TYPE`, make sure you are using any of these values:

```php
	$wp_environments = array(
		'local',
		'development',
		'staging',
		'production',
	);
```

If you are setting `WP_ENVIRONMENT_TYPE` to anything else it defaults to production ([read more here](https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/)).

---

I tried both and they are both working for me:

```php
define( 'WP_SENTRY_PUBLIC_DSN', 'https://asdasd@sentry.io/12345' );
define( 'WP_SENTRY_BROWSER_DSN', 'https://asdasd@sentry.io/12345' );
```

Make sure your host is not using opcache (or clear it) and that you add these `define` calls in your `wp-config.php`.

If that all is not working for some reason please let me know your PHP version and also what version of the plugin you are using.

**Comment by Giacomo92** [comment] 2021-06-29 15:35
Hi @stayallive, `WP_ENVIRONMENT_TYPE` is solved. I did not know it is a standard wordpress constant with a fixed amount of value.
 
`WP_SENTRY_BROWSER_DSN` still not working, I also try a filter in my function file:

```
/**
   * Customize public sentry dsn.
   *
   * @param string $dsn The current sentry public dsn.
   *
   * @return string
   */
  function oa_public_sentry_dsn( $dsn ) {
    return 'https://6e8a1089f5324d758778b185ccc8e2fd@o482126.ingest.sentry.io/5839000';
  }
  add_filter( 'wp_sentry_public_dsn', 'oa_public_sentry_dsn' );
```
but the JavaScript checkbox never get enabled.


**PHP Version:** 7.4.20
**Plugin Version:** 4.4.1


Thanks

**Comment by Giacomo92** [comment] 2021-06-29 15:48
Hi @stayallive, `WP_ENVIRONMENT_TYPE` is solved. I did not know it is a standard wordpress constant with a fixed amount of value.
 
`WP_SENTRY_BROWSER_DSN` still not working, I have also tried a filter in my function file:

```
/**
   * Customize public sentry dsn.
   *
   * @param string $dsn The current sentry public dsn.
   *
   * @return string
   */
  function oa_public_sentry_dsn( $dsn ) {
    return 'https://asdasd@sentry.io/12345';
  }
  add_filter( 'wp_sentry_public_dsn', 'oa_public_sentry_dsn' );
```
but the JavaScript checkbox never get enabled.


**PHP Version:** 7.4.20
**Plugin Version:** 4.4.1


Thanks

**Comment by stayallive** [comment] 2021-06-30 09:03
Yeah `WP_ENVIRONMENT_TYPE` is fixed indeed but you can use `WP_SENTRY_ENV` to put in anything you want.

The browser DSN is puzzling me why it will not work for you... I did make some changes to make the code a bit simpler for `4.5.0` of the plugin (just released) but I doubt it will solve your issue.

But I did not see if you are placing the `define( 'WP_SENTRY_BROWSER_DSN', 'https://asdasd@sentry.io/12345' );` in your `wp-config.php` file? 
Is it in the same place as the `define( 'WP_SENTRY_DSN', 'https://asdasd@sentry.io/12345' );`?

**Comment by Giacomo92** [comment] 2021-06-30 11:58
Now the checkbox is enabled. 
![Schermata 2021-06-30 alle 13 50 57](https://user-images.githubusercontent.com/11694429/123955755-429a2c80-d9aa-11eb-8687-ec918eaa0ac5.png)

When I try to send a Javascript test event I got this:
![Schermata 2021-06-30 alle 13 52 50](https://user-images.githubusercontent.com/11694429/123955910-77a67f00-d9aa-11eb-940a-fb62ffb6a054.png)

I notice that [wp-sentry-browser file ](https://github.com/stayallive/wp-sentry/blob/5b0e7c13bb232b2a47e2b92b39ed8d5e53f60e95/src/class-wp-sentry-js-tracker.php#L152) is not include in my page, so this condition is never satisfied and I always get the error:
`if (typeof Sentry === 'object' && typeof Sentry.captureMessage === 'function') {`

`WP_SENTRY_BROWSER_DSN` is right after `WP_SENTRY_PHP_DSN` in my wp-config.php file.

**Comment by stayallive** [comment] 2021-06-30 13:01
It's getting more interesting by the minute here :D

Happy to see changes to the plugin helped make it work... somehow...

But at least the JS tracker is enabled now so we can move forward!

Are you using a plugin to concatenate scripts and or styles that might be in play here?

You can see the code it hooks into `admin_enqueue_scripts` so I don't see how that wouldn't work unless something is messing with enqueues. You can also search your HTML for `var wp_sentry` which should always be there becomes that comes from the [localize script](https://github.com/stayallive/wp-sentry/blob/5b0e7c13bb232b2a47e2b92b39ed8d5e53f60e95/src/class-wp-sentry-js-tracker.php#L160-L167).

**Comment by stefs7** [comment] 2021-07-01 12:22
Hi, 

I'm also experiencing issues with WP_SENTRY_PHP_DSN & WP_SENTRY_BROWSER_DSN.
Using the latest WP plugin version (4.5.0) with the following defined in my wp-config:

```
define('WP_SENTRY_PHP_DSN', 'https://XXX');
define('WP_SENTRY_ERROR_TYPES', E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_USER_DEPRECATED);
define('WP_SENTRY_SEND_DEFAULT_PII', true);
define('WP_SENTRY_BROWSER_DSN', 'XXX');
```

OPcache & normal cache where emptied.

![image](https://user-images.githubusercontent.com/86782623/124123078-21ebd880-da77-11eb-9743-b79df1c1df5f.png)

**Comment by stayallive** [comment] 2021-07-01 12:56
Hey @stefs7 are you a new user or did you update the plugin from an earlier version?

Did you also put the `define`s above the `/* That's all, stop editing! Happy blogging. */` line in the `wp-config.php` file?

**Comment by stefs7** [comment] 2021-07-01 13:00
Hey Alex, 

Correct, I created my account today.
The `define`s are defined above the `/* That's all, stop editing! Happy blogging. */`.

Thanks for your fast reply!

**Comment by stayallive** [comment] 2021-07-01 13:04
Okay I'm super puzzled why this is an issue... I have copied your `define`s (but added correct DSN's of course) and it works just fine in my testing... so I must be missing something in my tests.

Can you also tell me what PHP version you are using and what version of WordPress so I can try to replicate?

**Comment by stefs7** [comment] 2021-07-01 13:33
PHP version: 7.2
WordPress (multisite): 5.7.2

I don't know for sure if I did use the correct keys.
I'm supposed to use the "DSN" key for `WP_SENTRY_PHP_DSN` & `WP_SENTRY_BROWSER_DSN` right?

![image](https://user-images.githubusercontent.com/86782623/124132966-a5aac280-da81-11eb-8ed4-032d63d66f2a.png)

**Comment by stayallive** [comment] 2021-07-01 14:17
Yes the values are indeed 90% of the time the same. But only the PHP SDK does some validation (and crashes hard if the value is invalid, needs to be fixed) but the browser DSN is not validated at all and only checked if it's not empty, so any value will be accepted there so that's why I am so puzzled why it's not working 😄 

I will try to figure it out with 7.2 and WP 5.7.

About multisite, did you enable the plugin site-wide or per site?

**Comment by stefs7** [comment] 2021-07-01 14:32
The plugin is site-wide: enabled for two domains (Dutch and Belgium).

Thanks for your help!

**Comment by stayallive** [comment] 2021-07-02 08:47
Hey @stefs7 I have tried to replicate the issue but I'm not getting anywhere :(

My `wp-config.php` looks like this for testing which might help you spot the problem in yours:

```php
<?php

/**
 * The base configuration for WordPress
 *
 * The wp-config.php creation script uses this file during the
 * installation. You don't have to use the web site, you can
 * copy this file to "wp-config.php" and fill in the values.
 *
 * This file contains the following configurations:
 *
 * * MySQL settings
 * * Secret keys
 * * Database table prefix
 * * ABSPATH
 *
 * @link https://codex.wordpress.org/Editing_wp-config.php
 *
 * @package WordPress
 */

define('WP_SENTRY_PHP_DSN', '<redacted>');
define('WP_SENTRY_BROWSER_DSN', '<redacted>');

define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', true);
define('DOMAIN_CURRENT_SITE', '<redacted>');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);

// ** MySQL settings ** //
/** The name of the database for WordPress */
define( 'DB_NAME', '<redacted>' );

/** MySQL database username */
define( 'DB_USER', '<redacted>' );

/** MySQL database password */
define( 'DB_PASSWORD', '<redacted>' );

/** MySQL hostname */
define( 'DB_HOST', '<redacted>' );

/** Database Charset to use in creating database tables. */
define( 'DB_CHARSET', 'utf8' );

/** The Database Collate type. Don't change this if in doubt. */
define( 'DB_COLLATE', '' );

/**
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * @since 2.6.0
 */
define('AUTH_KEY', '<redacted>');
define('SECURE_AUTH_KEY', '<redacted>');
define('LOGGED_IN_KEY', '<redacted>');
define('NONCE_KEY', '<redacted>');
define('AUTH_SALT', '<redacted>');
define('SECURE_AUTH_SALT', '<redacted>');
define('LOGGED_IN_SALT', '<redacted>');
define('NONCE_SALT', '<redacted>');

/**
 * WordPress Database Table prefix.
 *
 * You can have multiple installations in one database if you give each
 * a unique prefix. Only numbers, letters, and underscores please!
 */
$table_prefix = 'Rg6EsNn4_';

/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) )
	define( 'ABSPATH', dirname( __FILE__ ) . '/' );

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
```

Are you using some interesting deployment tools like Deployer or Capistrano or Bedrock or something to manage and/or update your WordPress installation? I'm grasping at straws here thinking about what could possibly be going wrong... I appreciate the patience and the info you are providing figuring this out!

**Comment by stefs7** [comment] 2021-07-06 11:47
Hi @stayallive, 

Sorry for my late reply.

I'm gonna try Sentry on a non-WordPress project first to exclude any other possible problems from my side.
Gonna let you know what my results are!

**Comment by stefs7** [comment] 2021-07-06 12:32
Update: problem was caused by a migration to a new server, so the changed wp-config with Sentry credentials was never used ._.
It instead loaded a different wp-config...

Bit of a dumb fault, sorry!

**Comment by stayallive** [comment] 2021-07-06 12:41
@stefs7 Woooops... well that would explain why it wasn't working, it happens! 😆 

Great to hear it was solved for you at least!

Now I only need to figure out what the issue with @Giacomo92 is, is the JS file loading now or is that still broken for you?

**Comment by dquinteros** [comment] 2021-07-22 15:31
> I have updated the plugin and now the checkbox is enabled.
> ![Schermata 2021-06-30 alle 13 50 57](https://user-images.githubusercontent.com/11694429/123955755-429a2c80-d9aa-11eb-8687-ec918eaa0ac5.png)
> 
> When I try to send a Javascript test event I got this:
> ![Schermata 2021-06-30 alle 13 52 50](https://user-images.githubusercontent.com/11694429/123955910-77a67f00-d9aa-11eb-940a-fb62ffb6a054.png)
> 
> I notice that [wp-sentry-browser file ](https://github.com/stayallive/wp-sentry/blob/5b0e7c13bb232b2a47e2b92b39ed8d5e53f60e95/src/class-wp-sentry-js-tracker.php#L152) is not include in my page, so this condition is never satisfied and I always get the error:
> `if (typeof Sentry === 'object' && typeof Sentry.captureMessage === 'function') {`
> 
> `WP_SENTRY_BROWSER_DSN` is right after `WP_SENTRY_PHP_DSN` in my wp-config.php file.

I have this same issue

**Comment by stayallive** [comment] 2021-07-22 15:34
Are you using a plugin to concatenate scripts and or styles that might be in play here or maybe even other caching plugins?

Can you try and disable all other plugins to see if it solves the problem? (do not do this on a production environment but only a test site).

**Comment by dquinteros** [comment] 2021-07-22 21:18
I do not use any specific plugin to concatenate scripts or styles, nor do I use any plugin for caching. I manage the cache mainly through cloudflare.

I will try to discard plugins compatibility  issues, will share my findings on the next days.

**Comment by stayallive** [comment] 2021-11-18 10:35
I am closing this issue because of inactivity, if there is still an issue please re-open / open a new issue so we can investigate 👍

**Closed by stayallive** 2021-11-18 10:35 UTC
Labels: question

**Comment by shintaii** [comment] 2022-03-11 08:06
Same issue here, i'm willing to help debug. 

So i have cleared OPcache and cache, there is no JS minifying. There are no sentry js scripts in my frontend session.

**Comment by stayallive** [comment] 2022-03-11 09:05
Hi @shintaii, please tell us a bit more about your environment, like what PHP version, what version of the plugin, what version of WordPress and what exactly you did configure in your `wp-config.php` file 👍

**Comment by shintaii** [comment] 2022-03-11 09:38
> Hi @shintaii, please tell us a bit more about your environment, like what PHP version, what version of the plugin, what version of WordPress and what exactly you did configure in your `wp-config.php` file 👍

Config file:
define( 'WP_SENTRY_PHP_DSN', 'https://123@567.ingest.sentry.io/890' );
define( 'WP_SENTRY_BROWSER_DSN', 'https://123@567.ingest.sentry.io/890' );
define( 'WP_SENTRY_BROWSER_TRACES_SAMPLE_RATE', 0.3 );

PHP version 7.4
plugin version:  4.14.0

**Comment by stayallive** [comment] 2022-04-01 15:27
@shintaii are you by chance running on a hosting provider that is using Lightspeed or have your site behind Cloudflare?

**Comment by Giacomo92** [comment] 2022-04-02 13:26
Hi @stayallive, sorry for my late reply. I am stil experiencing this issue. If it can be useful my website is behind Cloudflare

**Comment by shintaii** [comment] 2022-04-02 13:39
> 

Im using Kinsta, not sure what they use, but probably something like Cloudflare yes.
